### ISSUE TITLE
ResNet50 results mismatch between your readme and paper

### ISSUE THREAD

**Issue by meegoStar** [miaohxDLUT/SMPR#3]
Hi, thanks for sharing your nice work.

I am wondering why there is a mismatch between ResNet50 results in your [README table](https://github.com/miaohxDLUT/SMPR#results) (62.6 / 65.3*) and the ones reported in your paper (64.7 / 67.1*)?

**Comment by miaohxDLUT** [comment]
Thanks for your correction. The results in README table are before multi-scale training. I have already corrected it now.
